# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 768)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 11777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 251, 111))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 20, 81, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.brComboBox.setMaximumSize(QtCore.QSize(120, 22))
        self.brComboBox.setObjectName("brComboBox")
        self.verticalLayout.addWidget(self.brComboBox)
        self.clBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clBtn.setObjectName("clBtn")
        self.verticalLayout.addWidget(self.clBtn)
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(0, 30, 150, 61))
        self.splitter.setMaximumSize(QtCore.QSize(150, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.comboBox = QtWidgets.QComboBox(self.splitter)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.opnBtn = QtWidgets.QPushButton(self.splitter)
        self.opnBtn.setObjectName("opnBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(590, 60, 181, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.keyWordCB = QtWidgets.QComboBox(self.groupBox_2)
        self.keyWordCB.setGeometry(QtCore.QRect(30, 30, 141, 22))
        self.keyWordCB.setObjectName("keyWordCB")
        self.saveBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.saveBtn.setGeometry(QtCore.QRect(30, 100, 61, 28))
        self.saveBtn.setObjectName("saveBtn")
        self.factorFromJsonFileTB = QtWidgets.QTextEdit(self.groupBox_2)
        self.factorFromJsonFileTB.setGeometry(QtCore.QRect(30, 60, 141, 31))
        self.factorFromJsonFileTB.setObjectName("factorFromJsonFileTB")
        self.uploadBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.uploadBtn.setGeometry(QtCore.QRect(100, 100, 61, 28))
        self.uploadBtn.setObjectName("uploadBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "COM"))
        self.clBtn.setText(_translate("MainWindow", "Close"))
        self.opnBtn.setText(_translate("MainWindow", "Open"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Setting"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.uploadBtn.setText(_translate("MainWindow", "upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
